feat: Maui setup (#2)
* Add basic files

* Add basic checks for pull request

* Address nuget warnings

* Fix NoClassDefFoundError crash on sample app

* Add instructions for Android sample app

* Add iOS instructions

* Remove xcframework and replace with SPM wrapper

* Create build_xcframework.sh

* Export internal SDK and adjust import

* Changeover to package.swift

* Cleanup

* Correct library location

* Add workflow_dispatch

* Download aar on the fly

* Update to latest Android version

* Add new APIs for AudienceTask

* Remove env vars

* Add concurrency and PR notification to PR

* Change download method for AAR

* Add permissions

* Specify dotnet version

* Move download logic to build.sh

* Update pull-request.yml